- .gitignore
> gitignore 忽略 .DS_Store

- exercise/exercises/functions/README.md
- exercise/exercises/variables/README.md
- exercise/exercises/variables/variables1.rs
- exercise/exercises/variables/variables2.rs
- exercise/exercises/variables/variables3.rs
- exercise/exercises/variables/variables4.rs
- exercise/exercises/variables/variables5.rs
- exercise/exercises/variables/variables6.rs
- exercise/info.toml
> [rust-exercise] 翻译 variables 部分

- exercise/exercises/if/README.md
- exercise/exercises/if/if1.rs
- exercise/exercises/if/if2.rs
- exercise/info.toml
> [rust-exercise] 翻译 if 内的所有内容

- exercise/exercises/primitive_types/README.md
- exercise/exercises/primitive_types/primitive_types1.rs
- exercise/exercises/primitive_types/primitive_types2.rs
- exercise/exercises/primitive_types/primitive_types3.rs
- exercise/exercises/primitive_types/primitive_types4.rs
- exercise/exercises/primitive_types/primitive_types5.rs
- exercise/exercises/primitive_types/primitive_types6.rs
- exercise/info.toml
>  [rust-exercise] 翻译 primitive_types 内的所有内容

- course-book/contents/advance/functional-programing/closure.md
主要对 FnOnce 部分做了些修改，原先内容感觉不太切合。
> [3.3. 函数式编程] 闭包部分的一些优化

- exercise/exercises/structs/README.md
- exercise/exercises/structs/structs1.rs
- exercise/exercises/structs/structs2.rs
- exercise/exercises/structs/structs3.rs
- exercise/info.toml
> [rust-exercise] 翻译 structs 部分

- book/contents/advance/functional-programing/iterator.md
> [3.3.2. 迭代器iterator] JS 代码示例的一个小修复

- exercise/exercises/modules/README.md
- exercise/exercises/modules/modules1.rs
- exercise/exercises/modules/modules2.rs
- exercise/exercises/modules/modules3.rs
- exercise/info.toml
>  [rust-exercise] 翻译 modules 部分

- exercise/exercises/collections/README.md
- exercise/exercises/collections/hashmap1.rs
- exercise/exercises/collections/hashmap2.rs
- exercise/exercises/collections/vec1.rs
- exercise/exercises/collections/vec2.rs
- exercise/info.toml
>  [rust-exercise] 翻译 collections 部分

- exercise/exercises/strings/README.md
- exercise/exercises/strings/strings1.rs
- exercise/exercises/strings/strings2.rs
- exercise/info.toml
>  [rust-exercise] 翻译 strings 部分

- exercise/exercises/error_handling/README.md
- exercise/exercises/error_handling/errors1.rs
- exercise/exercises/error_handling/errors2.rs
- exercise/exercises/error_handling/errors3.rs
- exercise/exercises/error_handling/errors4.rs
- exercise/exercises/error_handling/errors5.rs
- exercise/exercises/error_handling/errors6.rs
- exercise/info.toml
> [rust-exercise] 翻译 error_handling 部分

- exercise/exercises/generics/generics1.rs
- exercise/exercises/generics/generics2.rs
- exercise/exercises/generics/generics3.rs
- exercise/info.toml
>  [rust-exercise] 翻译 generics 部分

- book/contents/basic/variable.md
> fix a typo in variable.md

- book/contents/basic/collections/hashmap.md
> fix: HashMap 章节 错别字

- book/contents/basic/result-error/panic.md
> fix: demo 代码运行结果错误，与实际不符

- exercise/exercises/generics/README.md
- exercise/exercises/option/README.md
- exercise/exercises/option/option1.rs
- exercise/exercises/option/option2.rs
- exercise/exercises/option/option3.rs
- exercise/info.toml
>  [rust-exercise] 翻译 option 部分

- exercise/exercises/traits/README.md
- exercise/exercises/traits/traits1.rs
- exercise/exercises/traits/traits2.rs
- exercise/info.toml
> [rust-exercise] 翻译 traits 部分

- book/contents/first-try/hello-world.md
修改过时描述。
测试链接
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=59e8d2ba4798c11d5c4f4e0280a90c52
> more detailed explanation

- exercise/exercises/tests/README.md
- exercise/exercises/tests/tests1.rs
- exercise/exercises/tests/tests2.rs
- exercise/exercises/tests/tests3.rs
- exercise/info.toml
>  [rust-exercise] 翻译 tests 部分

- book/contents/advance/crate-module/use.md
> Fixed typo

- contents/practice/naming.md
> fix wrong link

- README.md
update the starting link of the rust nomicon
> Update the link of Rust nomicon

- src/advance/functional-programing/iterator.md
感谢 sunface 编写这本对我等 Rust 初学者如此友好的入门书。
希望 rust sourse 能够能够越来越好
> 358 行第二句的“下面”与“们”之间缺少“我”

- src/tokio/shared-state.md
> fix Mutext

- src/index-list.md
> update(index-list): add hyperlink

- src/cargo/reference/workspaces.md
> fix(typo): workspacke => workspace

- src/advance/concurrency-with-threads/sync1.md
1. 补充了一个例子，应该可以更好的理解死锁
2. 统一了一些文字
> Fix typo in concurrency-with-threads/sync1.md

- src/index-list.md
> update(index-list): add three item

- src/index-list.md
> fix(index-list): add six items

- src/basic/compound-type/string-slice.md
> fix(string-slice): fix wrong link

- src/basic/compound-type/string-slice.md
因为是抄的别人的文章，所以应该加入版权声名
> ————————————————
> 版权声明：本文操作字符串部分节选自为 CSDN 博主「L 我是小学生」的原创文章，遵> 循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接及本声明。
> 原文链接：https://blog.csdn.net/a1595901624/article/details/119294443
这个应该加在什么地方？
> update(string_slice): 更新操作字符串的内容

- README.md
Reverts sunface/rust-course#668
> Revert "fix: zhihu icon"

- theme/style2.css
> fix: styles

- src/basic/result-error/panic.md
- src/basic/result-error/result.md
为 panic 和 result 添加末尾的练习题链接
🙏 感谢提供这么好的项目
> doc: add missing practices

- src/index-list.md
本来是想分三份提交的，但是对 git cherry-pick 不熟，只好一次性提交了
你受累审查
> update(index-list): update style, add Generics, add Trait

- src/first-try/cargo.md
- src/first-try/installation.md
虽然在网站上留了评论，思来想去还是自己提了个pr，希望后来的rust初学者能少浪费点时间
> 填上看本教程安装rust时我掉过的坑

- src/advance/circle-self-ref/self-referential.md
> fix: typo in circle-self-ref/self-referential.md

- src/async-rust/tokio/spawning.md
1. 增加简要`[[example]]`说明
2. 更新旧版本404链接
3. fix typo
> perf(tokio/spawning)

- src/basic/formatted-output.md
```diff
-    // 右对齐 => Hello     x
+    // 右对齐 => Hello     x!
println!("Hello {:>5}!", "x");
```
> fix: result of `println!`

- theme/index.hbs
- theme/style3.css
> feat: add viewed style

- src/cargo/reference/publishing-on-crates.io.md
> fix: typo pulish

- src/basic/formatted-output.md
> fix a typo in formatted-output.md

- src/first-try/cargo.md
> 修复文档的两个小bug

- src/advance/macro.md
> rich the derive macro content

- src/advance/macro.md
fix
1. 一些展示问题，例如 “#id” 这种在线阅读会变成空行， 所以中间加了个空格 改成 “# id”
2. 处理了代码的warning
> fix proc macro incorrect view and warning code

- src/SUMMARY.md
- src/appendix/rust-versions/1.68.md
> translation(appendix/rust-versions) : 1.68

- src/SUMMARY.md
- src/appendix/rust-versions/1.68.md
- src/appendix/rust-versions/1.69.md
> translation(appendix/rust-versions) : 1.69

- src/too-many-lists/ok-stack/iter.md
> Typo modification

- src/advance/concurrency-with-threads/sync1.md
修复 https://github.com/sunface/rust-course/issues/1218
> Fix typo in concurrency chapter, deadlock part

- src/basic/collections/vector.md
> 增加 vector 排序相关内容

- src/advance-practice/async.md
fixed the pin/unpin url which is broken and 404 occurs.
> fixed the pin/unpin broken url

- src/SUMMARY.md
- src/appendix/rust-versions/1.70.md
- src/appendix/rust-versions/1.71.md
🕊了很久... 个人前段时间不太稳定，现在也stable下来了😁
mark #1134
> translation(appendix/rust-versions) : 1.70-1.71

- src/SUMMARY.md
- src/appendix/rust-versions/1.72.md
> translation(appendix/rust-versions) : 1.72

- src/advance/concurrency-with-threads/sync1.md
Fix RwLock in sync1.md
Fixes: #1262
Signed-off-by: lisongqian <mail@lisongqian.cn>
> Fix RwLock in sync1.md

- theme/style.css
🐛 fix #1266 :  fixed page navigation
> 🐛 fix #1266 :  fixed page navigation

- src/advance/functional-programing/iterator.md
> Eliminate compiler warnings

- src/basic/compound-type/enum.md
> fix: update enum.md

- theme/style.css
> chore: add color to scrollbar thumb

- src/SUMMARY.md
- src/appendix/rust-versions/1.74.md
> translation(appendix/rust-versions) : 1.74

- src/advance/circle-self-ref/circle-reference.md
> fix: typo fix

- src/SUMMARY.md
- src/appendix/rust-versions/1.76.md
> translation(appendix/rust-versions) : 1.76

- src/basic/lifetime.md
cleanup: 代码块统一，便于粘贴复制用于测试
Before: 
After:
> cleanup: 代码块统一，便于粘贴复制用于测试

- src/SUMMARY.md
- src/appendix/rust-versions/1.77.md
> translation(appendix/rust-versions) : 1.77

- src/SUMMARY.md
- src/appendix/rust-versions/1.78.md
> translation(appendix/rust-versions) : 1.78

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- ci/copy-assets.sh
1. add ci script
2. add deploy script
> chore: add github action

- src/basic/compound-type/string-slice.md
> Update string-slice.md: remove 404 pages

- src/SUMMARY.md
- src/appendix/rust-versions/1.79.md
> translation(appendix/rust-versions) : 1.79

- src/basic/crate-module/crate.md
Removing the character '个' makes the sentence more fluent and easier to read。
> fix: Remove one Chinese character to make the meaning clearer

- src/SUMMARY.md
- src/appendix/rust-versions/1.80.md
> translation(appendix/rust-versions) : 1.80

- src/cargo/reference/features/intro.md
https://doc.rust-lang.org/cargo/reference/features.html#:~:text=any%20feature%20such%20as
> Fix typo in intro.md

- src/SUMMARY.md
- src/appendix/rust-versions/1.82.md
> translation(appendix/rust-versions) : 1.82

- src/SUMMARY.md
- src/appendix/rust-versions/1.83.md
> translation(appendix/rust-versions) : 1.83

- src/SUMMARY.md
- src/appendix/rust-versions/1.86.md
> translation(appendix/rust-versions) : 1.86

- src/advance/global-variable.md
LazyCell已经稳定，所以修改OnceCell小节，增加其用法。
> 更新 标准库中的 OnceCell 小节

- src/first-try/installation.md
> docs: add freebsd install rustup

- src/advance/errors.md
> docs: update errors.md
