book/contents/advance/crate-module/crate.md

”包和Package“ 运行示例的目录名错误

---

contents/basic/ownership/borrowing.md

Fix typo in basic/ownership/borrowing.md

---

contents/basic/base-type/function.md

牛津词典里面并没有`substract`这个词，加减的`减`更准确的说法是`minus`

更改“plus_or_substract”为“plus_or_minus”

---

src/basic/comment.md

在阅读 [2.13. 注释和文档](https://course.rs/basic/comment.html) 章节的 [同名项的跳转](https://course.rs/basic/comment.html#%E5%90%8C%E5%90%8D%E9%A1%B9%E7%9A%84%E8%B7%B3%E8%BD%AC) 栏目时，发现运行 `cargo doc --open` 无法显示。
原因是必须标记为 `pub`，示例代码漏了 `pub` 关键字，另外 `foo!` 也漏了 `#[macro_export]`，修正后的代码为：
```rust
/// 跳转到结构体  [`Foo`](struct@Foo)
pub struct Bar;
/// 跳转到同名函数 [`Foo`](fn@Foo)
pub struct Foo {}
/// 跳转到同名宏 [`foo!`]
pub fn Foo() {}
#[macro_export]
macro_rules! foo {
() => {}
}
```
预览效果：

Fixed comment some code.

---

src/advance/circle-self-ref/circle-reference.md

1. 修复拼写错误
2. 前面有提到 `Drop` 特征，在注释处我认为显示正确的销毁顺序更为合理

Fix typo in circle-self-ref/circle-reference.md

---

src/basic/comment.md

在 [2.13. 注释和文档 - 一个综合例子](https://course.rs/basic/comment.html#%E4%B8%80%E4%B8%AA%E7%BB%BC%E5%90%88%E4%BE%8B%E5%AD%90) 章节中，该例子测试案例存在两个问题：
1.  **枚举类型不能通过 `==` 判断相等性**
正确的做法应该是使用 `matches!` 模式匹配宏，如：
2. **如果有意写错代码，那应该添加 `should_panic` 标识**，如：
-----------------
最后结论，应该是采取第一种方式，采用 `matches!` 宏方式。

Fixed `cargo test` panic!

---

README.md

一个字的 icon 是刚刚那个链接
两个字的来自 zhihu cdn

fix: zhihu icon

---

src/advance/concurrency-with-threads/thread.md

在 [3.6.2. 使用多线程 - 只被调用一次的函数](https://course.rs/advance/concurrency-with-threads/thread.html#%E5%8F%AA%E8%A2%AB%E8%B0%83%E7%94%A8%E4%B8%80%E6%AC%A1%E7%9A%84%E5%87%BD%E6%95%B0) 章节中，示例代码使用了 `ONCE_INIT` 来初始化 `INIT`：
**实际上在 Rust v1.38.0 版本之后，该静态常量已经被标记过时，应该使用 `Once::new()` 代替**：
-----
官方标准库说明：https://doc.rust-lang.org/std/sync/constant.ONCE_INIT.html

Fixed deprecated code: `ONCE_INIT`->`Once::new()`

---

src/advance/smart-pointer/rc-arc.md

The iterator link at line 55 does not exist anymore

Update link in rc-arc md file

---

assets/custom.js

如果这里设置了data-lang，giscus会拼接url成 `https://giscus.app/{{data-lang-value}}/widget`。如果系统语言是giscus不支持的会404，例如`en-US` (giscus对于en类的，貌似只支持`en`，不支持地区)，去掉让giscus自己检测就好

fix: 强制设置lang导致giscus404

---

src/advance/unsafe/superpowers.md

在 [3.9.1 五种兵器 - 用安全抽象包裹 unsafe 代码](https://course.rs/advance/unsafe/superpowers.html#%E7%94%A8%E5%AE%89%E5%85%A8%E6%8A%BD%E8%B1%A1%E5%8C%85%E8%A3%B9-unsafe-%E4%BB%A3%E7%A0%81) 中代码存在调用歧义：

Fixed code typo

---

src/async-rust/tokio/select.md
src/async-rust/tokio/stream.md

看到了 `yield` 关键字，但是发现似乎没有有关类似的介绍，是否考虑翻译呢？

fix: typo and add example

---

src/test/ci.md

As stated in the document of `actions-rs/cargo@v1`, this action is not required usually, and we can use `cargo` command directly instead. For example, replace
```yaml
- uses: actions-rs/cargo@v1
with:
command: fmt
args: --all -- --check
```
with
```yaml
- run: cargo fmt --all -- --check
```

Update Ci: remove actions-rs/cargo@v1

---

src/basic/method.md

对于习惯了 `new` 作为关键字的普通程序员，下意识以为 `new` 是关键字；  
致使第一眼看到 `fn new` 以为是强制的写法，遂想补充说明下 `new` 非关键字

chore: 补充new说明

---

src/basic/trait/trait.md

docs: 措辞修改

---

src/appendix/operators.md

删除了两个不能在在切片中使用的示例: `..=` 和 `expr..=`

更正 appendix/operators 中 *闭合区间* 的示例

---

src/advance/functional-programing/closure.md

文中提到的[例子](https://practice.rs/functional-programing/cloure.html#closure-in-structs)，`E`有`Copy`的type bound，而`String`是没有实现`Copy`的。
```rust
struct Cacher<T,E>
where
T: Fn(E) -> E,
E: Copy
{
query: T,
value: Option<E>,
}
impl<T,E> Cacher<T,E>
where
T: Fn(E) -> E,
E: Copy
{
fn new(query: T) -> Cacher<T,E> {
Cacher {
query,
value: None,
}
}
fn value(&mut self, arg: E) -> E {
match self.value {
Some(v) => v,
None => {
let v = (self.query)(arg);
self.value = Some(v);
v
}
}
}
}
fn main() {
}
#[test]
fn call_with_different_values() {
let mut c = Cacher::new(|a| a);
let v1 = c.value(1);
let v2 = c.value(2);
assert_eq!(v2, 1);
}
```

the demo code can not cache `String` but `&str`

---

src/cargo/reference/manifest.md

SPDX2.1 协议表达式 的链接地址错误，原本链接到的页面是the book的不相关的小节(badge小节)，修复成链接到the book此链接所链接的页面

fix wrong link

---

src/advance/concurrency-with-threads/thread.md

[标准库 Condvar Example](https://doc.rust-lang.org/std/sync/struct.Condvar.html#examples)
```rust
// 标准库文档的写法
let (lock, cvar) = &*pair;
```
```rust
// 圣经目前的写法
let &(ref lock, ref cvar) = &*pair;
```
两种写法是等价的，但是圣经里的写法不够简洁，且会让初学者非常疑惑，建议改成标准库文档的写法。
（另外，是不是可以考虑出一期 & 和 ref 的用法总结和区别）

update thread.md about reference

---

src/basic/match-pattern/match-if-let.md

在学习章节 `2.11.2. 返回值 Result 和?` 时遇到一个新的match用法，之前没有提到过，所以在这里加上。 https://course.rs/basic/result-error/result.html#%E5%AF%B9%E8%BF%94%E5%9B%9E%E7%9A%84%E9%94%99%E8%AF%AF%E8%BF%9B%E8%A1%8C%E5%A4%84%E7%90%86

增加一个match的例子

---

src/too-many-lists/bad-stack/final-code.md

原文是“Bonus Section For Premature Optimization!”，意思是对“过早优化”的额外说明，bonus 说的是 section 不是优化的奖励。
另外删除了一行错误的代码块开头。
最后一行的换行符是在线编辑器自己弄的。

fix translation in too-many-lists

---

src/SUMMARY.md
src/appendix/rust-versions/1.72.md
src/appendix/rust-versions/1.73.md

translation(appendix/rust-versions) : 1.73

---

src/advance/macro.md

与前文不符，应使用 `cargo expand --bin hello_macro` in hello_macro root directory

fix cargo expand in macro.md

---

src/basic/collections/vector.md

初始化 vec 的更多方式：
```rust
fn main() {
let v = vec![0; 3];   // 默认值为 0，初始长度为 3
let v_from = Vec::from([0, 0, 0]);
assert_eq!(v, v_from);
}
```
动态数组意味着我们增加元素时，如果**容量不足就会导致 vector 扩容**（目前的策略是重新申请一块 2 倍大小的内存，再将所有元素拷贝到新的内存位置，同时更新指针数据），显然，当频繁扩容或者当元素数量较多且需要扩容时，大量的内存拷贝会降低程序的性能。
可以考虑在初始化时就指定一个实际的预估容量，尽量减少可能的内存拷贝：
```rust
fn main() {
let mut v = Vec::with_capacity(10);
v.extend([1, 2, 3]);    // 附加数据到 v
println!("Vector 长度是: {}, 容量是: {}", v.len(), v.capacity());
v.reserve(100);        // 调整 v 的容量，至少要有 100 的容量
println!("Vector（reserve） 长度是: {}, 容量是: {}", v.len(), v.capacity());
v.shrink_to_fit();     // 释放剩余的容量，一般情况下，不会主动去释放容量
println!("Vector（shrink_to_fit） 长度是: {}, 容量是: {}", v.len(), v.capacity());
}
```
Vector 常见的一些方法示例：
```rust
let mut v =  vec![1, 2];
assert!(!v.is_empty());         // 检查 v 是否为空 …
```

增加基础入门-复合类型-动态数据Vector中的 Vector常见方法 内容

---

src/SUMMARY.md
src/appendix/rust-versions/1.75.md

translation(appendix/rust-versions) : 1.75

---

src/cargo/reference/features/intro.md

目前rustc --cfg的写法很粗略，这里增加了一个示例，方便大家理解rustc --cfg选项的用法

增加更精确的rustc --cfg使用方法

---

src/basic/trait/generic.md

添加了空格，与上下文风格保持一致（473行我没有作出修改，但是git把这行标出来了，然而我肉眼没有看出区别）

style: Fix whitespace in generic.md

---

src/basic/compound-type/string-slice.md

References:
[Rust By Example](https://doc.rust-lang.org/rust-by-example/std/str.html#literals-and-escapes)
```rust
fn main() {
let raw_str = r"Escapes don't work here: \x3F \u{211D}";
println!("{}", raw_str);
// If you need quotes in a raw string, add a pair of #s
let quotes = r#"And then I said: "There is no escape!""#;
println!("{}", quotes);
// If you need "# in your string, just use more #s in the delimiter.
// You can use up to 255 #s.
let longer_delimiter = r###"A string with "# in it. And even "##!"###;
println!("{}", longer_delimiter);
}
```

Modify string-slice.md

---

src/basic/match-pattern/option.md

由于`None<Some(T)`为`true`(如果`T:PartialOrd`)
所以Option的枚举中，`None`在前，`Some`在后，这个顺序最好不要更改

修正Option的排序

---

src/basic/base-type/numbers.md

修改示例数据类型为u8。原先的i32长度过长不便01二进制展示；且取反操作会一同反转符号位，或许会造成读者疑惑。
展示输出中使用`{:08b}`格式化并对齐，应该更加直观。
修改后的运行效果如下
```powershell
PS D:\pro\rustworks\playground\demo_binop> cargo run
Finished dev [unoptimized + debuginfo] target(s) in 0.07s
Running `target\debug\demo_binop.exe`
a value is        00000010
b value is        00000011
(a & b) value is  00000010
(a | b) value is  00000011
(a ^ b) value is  00000001
(!b) value is     11111100
(a << b) value is 00010000
(a >> b) value is 00000000
(a << b) value is 00010000
```

修改位操作示例展示效果

---

src/basic/crate-module/module.md

doc: 让文件和mod的对应更清晰
我看的时候有点迷糊，没get到位，看了 https://doc.rust-lang.org/book/ch07-05-separating-modules-into-different-files.html 才理解到位了

doc: 让文件和mod的对应更清晰

---

src/SUMMARY.md
src/appendix/rust-versions/1.81.md

translation(appendix/rust-versions) : 1.81

---

src/SUMMARY.md
src/appendix/rust-versions/1.84.md
src/appendix/rust-versions/1.85.md

translation(appendix/rust-versions) : 1.84 && 1.85

---

src/basic-practice/base-features.md

`std::env` 和 `std::fs` 应当描述为 `std` **包**（`crate`）中的 `env` 和 `fs` **模块**（`module`）

勘误：包和模块描述的准确性

---

src/basic/base-type/function.md

去掉函数要点部分的例子中 `add_two` 不正确的 `->` 使用，这里的 `add_two` 显然是没有返回值的，应该不用加 `->`

修改 function.md 中的一处小错误
